# Generated by Django 5.2.7 on 2025-10-05 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrgUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="persons",
                        to="hse.contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActionForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("indicator", models.CharField(max_length=7, unique=True)),
                ("requester_name", models.CharField(max_length=255)),
                ("requester_unit_text", models.CharField(max_length=255)),
                ("request_date", models.DateField()),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("CORRECTIVE", "Corrective"),
                            ("PREVENTIVE", "Preventive"),
                            ("CHANGE", "Change"),
                            ("SUGGESTION", "Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sources", models.JSONField(blank=True, default=list)),
                ("nonconformity_or_change_desc", models.TextField()),
                ("root_cause_or_goal_desc", models.TextField()),
                ("needs_risk_update", models.BooleanField(default=False)),
                ("risk_update_date", models.DateField(blank=True, null=True)),
                ("creates_knowledge", models.BooleanField(default=False)),
                (
                    "approved_by_performer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "approved_by_manager_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("exec1_approved", models.BooleanField(blank=True, null=True)),
                ("exec1_note", models.TextField(blank=True, null=True)),
                ("exec1_new_date", models.DateField(blank=True, null=True)),
                ("exec2_approved", models.BooleanField(blank=True, null=True)),
                ("exec2_note", models.TextField(blank=True, null=True)),
                ("exec2_new_date", models.DateField(blank=True, null=True)),
                ("effectiveness_checked_at", models.DateField(blank=True, null=True)),
                ("effectiveness_method_text", models.TextField(blank=True, null=True)),
                ("effective", models.BooleanField(blank=True, null=True)),
                (
                    "new_action_indicator",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actions",
                        to="hse.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("prepared_by_name", models.CharField(max_length=255)),
                ("approved_by_name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="safety_teams",
                        to="hse.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "org_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="hse.orgunit",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RiskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("process_title", models.CharField(max_length=255)),
                ("activity_desc", models.TextField()),
                (
                    "routine_flag",
                    models.CharField(
                        choices=[("R", "Routine"), ("N", "Non Routine")], max_length=1
                    ),
                ),
                ("hazard_desc", models.TextField()),
                ("event_desc", models.TextField()),
                ("consequence_desc", models.TextField()),
                ("root_cause_desc", models.TextField()),
                ("existing_controls_desc", models.TextField()),
                ("inputs", models.JSONField(blank=True, default=list)),
                ("legal_requirement_text", models.TextField(blank=True)),
                (
                    "legal_status",
                    models.CharField(
                        choices=[
                            ("COMPLIANT", "Compliant"),
                            ("NONCOMPLIANT", "Non Compliant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_type",
                    models.CharField(
                        choices=[
                            ("SAFETY", "Safety"),
                            ("HEALTH", "Health"),
                            ("PROPERTY", "Property"),
                        ],
                        max_length=20,
                    ),
                ),
                ("A", models.PositiveIntegerField()),
                ("B", models.PositiveIntegerField()),
                ("C", models.PositiveIntegerField()),
                ("E", models.PositiveIntegerField(editable=False)),
                ("S", models.PositiveIntegerField()),
                ("P", models.PositiveIntegerField(editable=False)),
                ("D", models.PositiveIntegerField()),
                ("RPN", models.PositiveIntegerField(editable=False)),
                (
                    "acceptance",
                    models.CharField(
                        choices=[
                            ("L_ACCEPTABLE", "Low acceptable"),
                            ("H_UNACCEPTABLE", "High unacceptable"),
                            ("LEGAL_NONCOMPLIANT", "Legal noncompliant"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "action_number_text",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("A2", models.PositiveIntegerField(blank=True, null=True)),
                ("B2", models.PositiveIntegerField(blank=True, null=True)),
                ("C2", models.PositiveIntegerField(blank=True, null=True)),
                ("E2", models.PositiveIntegerField(blank=True, null=True)),
                ("S2", models.PositiveIntegerField(blank=True, null=True)),
                ("P2", models.PositiveIntegerField(blank=True, null=True)),
                ("D2", models.PositiveIntegerField(blank=True, null=True)),
                ("RPN2", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "acceptance2",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("L_ACCEPTABLE", "Low acceptable"),
                            ("H_UNACCEPTABLE", "High unacceptable"),
                            ("LEGAL_NONCOMPLIANT", "Legal noncompliant"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
                (
                    "action_number_text2",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks",
                        to="hse.project",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks",
                        to="hse.orgunit",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risks",
                        to="hse.section",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_code", models.CharField(max_length=10)),
                ("year2", models.CharField(max_length=2)),
                ("last_serial", models.PositiveIntegerField(default=0)),
            ],
            options={
                "unique_together": {("origin_code", "year2")},
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("representative_name", models.CharField(max_length=255)),
                ("signature_text", models.CharField(blank=True, max_length=255)),
                ("tbm_no", models.CharField(blank=True, max_length=50)),
                (
                    "contractor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hse.contractor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hse.section",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="hse.safetyteam",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hse.orgunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ToolboxMeeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("tbm_no", models.CharField(max_length=50, unique=True)),
                ("date", models.DateField()),
                ("topic_text", models.CharField(max_length=255)),
                ("trainer_text", models.CharField(max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="toolbox_meetings",
                        to="hse.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TBMAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("full_name", models.CharField(max_length=255)),
                ("role_text", models.CharField(max_length=255)),
                ("signature_text", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tbm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="hse.toolboxmeeting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("description_text", models.TextField()),
                ("resources_text", models.TextField()),
                ("due_date", models.DateField()),
                ("owner_text", models.CharField(max_length=255)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="hse.actionform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action"], name="hse_actioni_action__e025a8_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ActionTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("issue_desc", models.TextField()),
                ("action_desc", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUDIT", "AUDIT"),
                            ("LEGAL", "LEGAL"),
                            ("PROCESS_RISKS", "PROCESS_RISKS"),
                            ("INCIDENTS", "INCIDENTS"),
                            ("NEAR_MISS", "NEAR_MISS"),
                            ("UNSAFE_CONDITION", "UNSAFE_CONDITION"),
                            ("UNSAFE_ACT", "UNSAFE_ACT"),
                            ("CHECKLIST", "CHECKLIST"),
                            ("HSE_RISKS", "HSE_RISKS"),
                            ("ENV_ASPECTS", "ENV_ASPECTS"),
                            ("MGT_REVIEW", "MGT_REVIEW"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=30,
                    ),
                ),
                ("executor_text", models.CharField(max_length=255)),
                ("due_date", models.DateField()),
                ("review_date_1", models.DateField(blank=True, null=True)),
                ("review_date_2", models.DateField(blank=True, null=True)),
                ("review_date_3", models.DateField(blank=True, null=True)),
                ("resolved", models.BooleanField(blank=True, null=True)),
                ("is_knowledge", models.BooleanField(blank=True, null=True)),
                ("effective", models.BooleanField(blank=True, null=True)),
                (
                    "new_action_indicator",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trackings",
                        to="hse.actionform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "is_deleted"],
                        name="hse_actiont_action__04297d_idx",
                    ),
                    models.Index(
                        fields=["resolved"], name="hse_actiont_resolve_106974_idx"
                    ),
                    models.Index(
                        fields=["effective"], name="hse_actiont_effecti_4699f3_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("subject_text", models.TextField()),
                ("date_registered", models.DateField()),
                ("date_applied", models.DateField()),
                ("owner_text", models.CharField(max_length=255)),
                ("required_actions_text", models.TextField()),
                ("related_action_no_text", models.CharField(blank=True, max_length=50)),
                ("notes_text", models.TextField(blank=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="hse.actionform",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["action", "is_deleted"],
                        name="hse_changel_action__734890_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="actionform",
            index=models.Index(
                fields=["indicator"], name="hse_actionf_indicat_f47511_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionform",
            index=models.Index(
                fields=["project", "is_deleted"], name="hse_actionf_project_9c10eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionform",
            index=models.Index(
                fields=["request_type"], name="hse_actionf_request_63a267_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionform",
            index=models.Index(
                fields=["effective"], name="hse_actionf_effecti_c8b06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionform",
            index=models.Index(
                fields=["created_at"], name="hse_actionf_created_e54d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safetyteam",
            index=models.Index(
                fields=["project", "is_deleted"], name="hse_safetyt_project_9dfab2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="safetyteam",
            index=models.Index(
                fields=["created_at"], name="hse_safetyt_created_a02398_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["project", "is_deleted"], name="hse_riskrec_project_84e522_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["acceptance"], name="hse_riskrec_accepta_9f1387_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskrecord",
            index=models.Index(
                fields=["created_at"], name="hse_riskrec_created_71d47b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teammember",
            index=models.Index(fields=["team"], name="hse_teammem_team_id_def9be_idx"),
        ),
        migrations.AddIndex(
            model_name="toolboxmeeting",
            index=models.Index(
                fields=["project", "is_deleted"], name="hse_toolbox_project_8ee74d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tbmattendee",
            index=models.Index(fields=["tbm"], name="hse_tbmatte_tbm_id_011e99_idx"),
        ),
    ]
