# Generated by Django 5.2.7 on 2025-10-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hse", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionform",
            name="indicator",
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name="actionform",
            name="new_action_indicator",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="actiontracking",
            name="new_action_indicator",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
