# Generated by Django 5.2.7 on 2025-10-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hse", "0004_toolboxmeeting_location_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="contact_info",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
