# Generated by Django 5.2.7 on 2025-10-16 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hse", "0005_teammember_contact_info"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("ARCHIVED", "Archived")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="project_end_date_after_start_date",
            ),
        ),
    ]
